### ISSUE TITLE
STAR incompatibility

### ISSUE THREAD

**Issue by erikmcintire** [aselewa/dropseqRunner#4]
Hello,

I am attempting to use dropseqRunner to process fastq files on the UC cluster, but keep running into the following error and would appreciate any guidance you can provide:
"EXITING because of FATAL ERROR: Genome version: 20201 is INCOMPATIBLE with running STAR version: 2.7.6a
SOLUTION: please re-generate genome from scratch with running version of STAR, or with version: 2.7.4a"

For indices generation, I used the STAR module from the UC RCC, STAR/2.6.1b(default), to generate indices using a fasta file and GTF annotations from the linked GENOME website. For the GTF file I used Comprehensive gene annotation (Region: CHR) and for the fasta file I used Genome sequence (GRCh38.p13) (Region: ALL). 

I have attached my batch script and the error output:
[error_output.txt](https://github.com/aselewa/dropseqRunner/files/5495632/error_output.txt)
[bash_script.txt](https://github.com/aselewa/dropseqRunner/files/5495633/bash_script.txt)

Please let me know if I may provide ant additional information, thank you for your time.

**Comment by aselewa** [comment]
Hi,

It appears you are using 2 different STAR versions: 2.6.1b to make the genomic index, and 2.7.6a to do the alignment. This is not advisable because STAR frequently updates how the genomic indices are generated with newer versions and it is not backwards compatible. 

I recommend you use the STAR version in the conda environment provided (2.7.6a) for both index generation and alignment.

**Comment by aselewa** [comment]
Feel free to open this again if the issue persists
